const { __ } = window.wp.i18n;

export default {
    ADMIN_PAGE: __('ELO Ranking Manager', 'memberdata-ranking'),
    TAB_MATCHES: __('Matches', 'memberdata-ranking'),
    TAB_RANKING: __('Ranking', 'memberdata-ranking'),
    TAB_SETTINGS: __('Settings', 'memberdata-ranking'),
    DESCR1: __('The formula used is as follows. Given a match between two participants A and B, scoring Pa points (participant A) and Pb points (participant B), and given the original ranking Ra and Rb and the configuration values below:', 'memberdata-ranking'),
    SA_INFO: __('with Va = 1 if A wins and Va = 0 if A loses', 'memberdata-ranking'),
    PLEASEADJUST: __('Please adjust the configuration settings as you seem fit.', 'memberdata-ranking'),
    BASERANK: __('Rank base', 'memberdata-ranking'),
    BASERANK_INFO: __('The base rank is the starting value for new participants. Default value of 1000.', 'memberdata-ranking'),
    KVALUE: __('K-value', 'memberdata-ranking'),
    KVALUE_INFO: __('The K-value determines the amount of points a participant receives or loses at most when they win a match. This number is adjusted according to the actual result with respect to the expected result. The default value is 32.', 'memberdata-ranking'),
    CVALUE: __('C-value', 'memberdata-ranking'),
    CVALUE_INFO: __('The C-value determines the factor with which expectations are compared. Large C values make it more difficult to determine an expected score difference between two fencers (everyone seems to be of more or less the same rank), whereas small C-values exagerate small ranking differences and will cause people to continuously switch after entering match results. The default value is 400.', 'memberdata-ranking'),
    NAME: __('Name', 'memberdata-ranking'),
    NAME_INFO: __('Select the attribute to use as name field', 'memberdata-ranking'),
    GROUP: __('Group', 'memberdata-ranking'),
    GROUP_INFO: __('Select the attribute to use as a grouping field', 'memberdata-ranking'),
    GROUPS: __('Values', 'memberdata-ranking'),
    GROUPS_INFO: __('Select the valid groups', 'memberdata-ranking'),
    CONFIG_SAVED: __('Configuration saved', 'memberdata-ranking'),
    SAVE: __('Save', 'memberdata-ranking'),
    CANCEL: __('Cancel', 'memberdata-ranking'),
    REMOVE: __('Remove', 'memberdata-ranking'),
    ALL: __('All', 'memberdata-ranking'),
    REASSESS: __('Reassess', 'memberdata-ranking'),
    ADD: __('Add', 'memberdata-ranking'),
    MSG_REASSESSED: __("Matches reassessed", 'memberdata-ranking'),
    CONFIRM_DELETE_MATCH: __('Are you sure you want to remove this match permanently?', 'memberdata-ranking'),
    MATCH_VALID_PLAYER1: __("Please pick a valid player for player 1", 'memberdata-ranking'),
    MATCH_VALID_PLAYER2: __("Please pick a valid player for player 2", 'memberdata-ranking'),
    MATCH_NO_DOUBLE_PLAYER: __("Person cannot score against him/herself", 'memberdata-ranking'),
    MATCH_VALID_DATE: __("Please enter a valid date or date-time for the match", 'memberdata-ranking'),
    MATCH_VALID_SCORE1: __("Please enter a valid score for player 1", 'memberdata-ranking'),
    MATCH_VALID_SCORE2: __("Please enter a valid score for player 2", 'memberdata-ranking'),
    ERROR_MATCH_SAVE: __("There was a problem storing this match's data. Please see if the data is allright and/or reload the page", 'memberdata-ranking'),
    ERROR_NETWORK: __("There was a network problem saving the data. Please try again or reload the page", 'memberdata-ranking'),
    ERROR_NETWORK_GEN: __('Network error, please try again', 'memberdata-ranking'),
    ERROR_VALIDATION: __('Validation', 'memberdata-ranking'),
    ERROR_PLAYERS: __('There was a problem retrieving the list of players. Please try again', 'memberdata-ranking'),
    DIALOG_MATCH: __('Edit Match Information', 'memberdata-ranking'),
    PLAYER1: __('Player 1', 'memberdata-ranking'),
    PLAYER2: __('Player 2', 'memberdata-ranking'),
    PLAYERS: __('Players', 'memberdata-ranking'),
    PICKPLAYER: __('Pick a player', 'memberdata-ranking'),
    SCORE1: __('Score Player 1', 'memberdata-ranking'),
    SCORE2: __('Score Player 2', 'memberdata-ranking'),
    SCORE: __('Score', 'memberdata-ranking'),
    RANK: __('Rank', 'memberdata-ranking'),
    NAME: __('Name', 'memberdata-ranking'),
    MATCHDATE: __('Date', 'memberdata-ranking'),
    UNKNOWNPLAYER: __('N.N.', 'memberdata-ranking'),
    DATEFORMATWITHOUTMINUTES: __('YYYY-MM-DD HH:mm', 'memberdata-ranking'),
};
